image:
  file: .gitpod.Dockerfile

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview

tasks:
  - before: pip install poetry
    init: poetry install
    command: poetry env use python

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
